#debug: true
server:
  port: 8083
  servlet:
    context-path: /basics
spring:
  datasource:
     #driver-class-name: oracle.jdbc.driver.OracleDriver
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
#     url: jdbc:oracle:thin:@localhost:1521:xe
     url: jdbc:mysql://47.105.181.242:3306/basics?user=root&amp;password=root&amp;autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8
     type: com.zaxxer.hikari.HikariDataSource
     hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual
  data:
    elasticsearch:
      cluster-name: master
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true


    #mvc:
   # static-path-pattern: /static/**
  logging:
    level:
      root: debug
  org:
    springframework:
      web: debug
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
  rabbitmq:
    host: 47.105.181.242
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        acknowledge-mode: manual
        prefetch: 5
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

#security:basic:enabled: false

#swagger-ui.html
swagger:
   enabled : true

jwt:
  token:
    expiresSecond: 172800
    base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=

snmp:
    timeout: 8000
    community: public
    ip : 47.105.181.242

redis :
    #ip : 47.105.181.242
    ip : 127.0.0.1
    port : 6379

elasticsearch:
  userIndex : user
  userIndexType : content

wx:
  appId: wxf34486aa25fe3425
  appSecret: 4f5baf61c0477ed7129ad7cbc2a7796a








